// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetConversation(arg1:string):Promise<Array<domain.Message>>;

export function GetProjects():Promise<Array<domain.Project>>;

export function GetSessions():Promise<Record<string, domain.Session>>;

export function KillSession(arg1:string):Promise<void>;

export function RemoveAgent(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespawnProject(arg1:string):Promise<Record<string, string>>;

export function SaveProjects(arg1:Array<domain.Project>):Promise<void>;

export function SendInput(arg1:Array<string>,arg2:string):Promise<void>;

export function SendRaw(arg1:string,arg2:string):Promise<void>;

export function SpawnAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
