// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function AddKBDoc(arg1:string,arg2:string):Promise<string>;

export function CheckTokens(arg1:string):Promise<Record<string, number>>;

export function CompressAgent(arg1:string):Promise<string>;

export function GetConversation(arg1:string):Promise<Array<domain.Message>>;

export function GetKBChunks(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProjects():Promise<Array<domain.Project>>;

export function GetSessions():Promise<Record<string, domain.Session>>;

export function GetSettings():Promise<Record<string, string>>;

export function KillSession(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReindexKB(arg1:string):Promise<string>;

export function RemoveAgent(arg1:string):Promise<void>;

export function RemoveKBDoc(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespawnProject(arg1:string):Promise<Record<string, string>>;

export function SaveProjects(arg1:Array<domain.Project>):Promise<void>;

export function SaveSettings(arg1:string,arg2:boolean):Promise<string>;

export function SearchChunks(arg1:string,arg2:string,arg3:number):Promise<Array<main.ChunkHit>>;

export function SendInput(arg1:Array<string>,arg2:string):Promise<void>;

export function SendRaw(arg1:string,arg2:string):Promise<void>;

export function SpawnAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SpawnShell(arg1:string):Promise<string>;

export function WipeSQLite():Promise<string>;
