// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespawnProject(arg1) {
  return window['go']['main']['App']['RespawnProject'](arg1);
}

export function SaveProjects(arg1) {
  return window['go']['main']['App']['SaveProjects'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendRaw(arg1, arg2) {
  return window['go']['main']['App']['SendRaw'](arg1, arg2);
}

export function SpawnAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2, arg3, arg4, arg5);
}
