// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codeview} from '../models';
import {domain} from '../models';
import {main} from '../models';

export function AddKBDoc(arg1:string,arg2:string):Promise<string>;

export function CheckTokens(arg1:string):Promise<Record<string, number>>;

export function CompressAgent(arg1:string):Promise<string>;

export function GetCommits(arg1:string,arg2:number):Promise<Array<codeview.Commit>>;

export function GetConversation(arg1:string):Promise<Array<domain.Message>>;

export function GetDiffFiles(arg1:string,arg2:string):Promise<Array<codeview.FileDiff>>;

export function GetFilePatch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetKBChunks(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProjectConfig(arg1:string):Promise<domain.ProjectConfig>;

export function GetProjects():Promise<Array<domain.Project>>;

export function GetSessions():Promise<Record<string, domain.Session>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSymbolGraph(arg1:string,arg2:string):Promise<codeview.SymbolGraph>;

export function KillSession(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReindexKB(arg1:string):Promise<string>;

export function RemoveAgent(arg1:string):Promise<void>;

export function RemoveKBDoc(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespawnProject(arg1:string):Promise<Record<string, string>>;

export function SaveProjectConfig(arg1:string,arg2:domain.ProjectConfig):Promise<string>;

export function SaveProjects(arg1:Array<domain.Project>):Promise<void>;

export function SaveSettings(arg1:string,arg2:boolean):Promise<string>;

export function SearchChunks(arg1:string,arg2:string,arg3:number):Promise<Array<main.ChunkHit>>;

export function SendInput(arg1:Array<string>,arg2:string):Promise<void>;

export function SendRaw(arg1:string,arg2:string):Promise<void>;

export function SpawnAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SpawnShell(arg1:string):Promise<string>;

export function WipeSQLite():Promise<string>;
