// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKBDoc(arg1, arg2) {
  return window['go']['main']['App']['AddKBDoc'](arg1, arg2);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetKBChunks(arg1, arg2) {
  return window['go']['main']['App']['GetKBChunks'](arg1, arg2);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReindexKB(arg1) {
  return window['go']['main']['App']['ReindexKB'](arg1);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function RemoveKBDoc(arg1, arg2) {
  return window['go']['main']['App']['RemoveKBDoc'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespawnProject(arg1) {
  return window['go']['main']['App']['RespawnProject'](arg1);
}

export function SaveProjects(arg1) {
  return window['go']['main']['App']['SaveProjects'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SearchChunks(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchChunks'](arg1, arg2, arg3);
}

export function SearchContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchContext'](arg1, arg2, arg3);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendRaw(arg1, arg2) {
  return window['go']['main']['App']['SendRaw'](arg1, arg2);
}

export function SpawnAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2, arg3, arg4, arg5);
}

export function WipeSQLite() {
  return window['go']['main']['App']['WipeSQLite']();
}
