// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKBDoc(arg1, arg2) {
  return window['go']['main']['App']['AddKBDoc'](arg1, arg2);
}

export function BuildPrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildPrompt'](arg1, arg2, arg3, arg4);
}

export function CheckTokens(arg1) {
  return window['go']['main']['App']['CheckTokens'](arg1);
}

export function CompressAgent(arg1) {
  return window['go']['main']['App']['CompressAgent'](arg1);
}

export function ExpandSymbol(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExpandSymbol'](arg1, arg2, arg3);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetBranchesForRepo(arg1, arg2) {
  return window['go']['main']['App']['GetBranchesForRepo'](arg1, arg2);
}

export function GetCommitDetail(arg1, arg2) {
  return window['go']['main']['App']['GetCommitDetail'](arg1, arg2);
}

export function GetCommits(arg1, arg2) {
  return window['go']['main']['App']['GetCommits'](arg1, arg2);
}

export function GetCommitsBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitsBranch'](arg1, arg2, arg3);
}

export function GetCommitsForRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCommitsForRepo'](arg1, arg2, arg3, arg4);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetDiffFiles(arg1, arg2) {
  return window['go']['main']['App']['GetDiffFiles'](arg1, arg2);
}

export function GetFilePatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFilePatch'](arg1, arg2, arg3);
}

export function GetGitRepos(arg1) {
  return window['go']['main']['App']['GetGitRepos'](arg1);
}

export function GetKBChunks(arg1, arg2) {
  return window['go']['main']['App']['GetKBChunks'](arg1, arg2);
}

export function GetProjectConfig(arg1) {
  return window['go']['main']['App']['GetProjectConfig'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSymbolGraph(arg1, arg2) {
  return window['go']['main']['App']['GetSymbolGraph'](arg1, arg2);
}

export function IsAgentBusy(arg1) {
  return window['go']['main']['App']['IsAgentBusy'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReadSymbolCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadSymbolCode'](arg1, arg2, arg3, arg4);
}

export function ReindexKB(arg1) {
  return window['go']['main']['App']['ReindexKB'](arg1);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function RemoveKBDoc(arg1, arg2) {
  return window['go']['main']['App']['RemoveKBDoc'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespawnProject(arg1) {
  return window['go']['main']['App']['RespawnProject'](arg1);
}

export function SaveProjectConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectConfig'](arg1, arg2);
}

export function SaveProjects(arg1) {
  return window['go']['main']['App']['SaveProjects'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SearchChunks(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchChunks'](arg1, arg2, arg3);
}

export function SearchMessagesForCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMessagesForCode'](arg1, arg2, arg3);
}

export function SearchSymbol(arg1, arg2) {
  return window['go']['main']['App']['SearchSymbol'](arg1, arg2);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendRaw(arg1, arg2) {
  return window['go']['main']['App']['SendRaw'](arg1, arg2);
}

export function SpawnAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2, arg3, arg4, arg5);
}

export function SpawnShell(arg1) {
  return window['go']['main']['App']['SpawnShell'](arg1);
}

export function SuggestSymbols(arg1, arg2) {
  return window['go']['main']['App']['SuggestSymbols'](arg1, arg2);
}

export function WipeSQLite() {
  return window['go']['main']['App']['WipeSQLite']();
}
